TestCase Bounding Box of Line
ROSA-project/ROSA-code pull request #29
Opened 2022-08-12 21:09 UTC by mehdi138r

#1-add comment, testcase for bounding box of line shape(cylinder with… 0 radius)

2022-08-13 13:08 UTC, saeedafra requested changes

2022-08-13 13:08 UTC, saeedafra commented on src/tests/bounding_box_test_input.json
> +  "comment":["rotation_angle : the ange of axis(phi and theta) for rotate"
typo angle
for rotation. for + a noun. Here "rotate" is a verb form

2022-08-13 13:08 UTC, saeedafra commented on src/tests/bounding_box_test_input.json
> +  "comment":["rotation_angle : the ange of axis(phi and theta) for rotate"
and anyway it's not clear. angle of what axis?

2022-08-13 13:08 UTC, saeedafra commented on src/tests/bounding_box_test_input.json
> +            ,"dimension : dimension of shapes that rotate"
define each element

2022-08-13 13:08 UTC, saeedafra commented on src/tests/bounding_box_test_input.json
> +            ,"expected_dimension_box : dimension of bounding box of shape that we expected "],
define elements

2022-08-17 16:16 UTC, erfanz commented
@mehdi138r 
Using concrete numbers in test cases, especially with multi-digit fractions (e.g. `1.4142135624`), should generally be avoided as it makes the code cryptic and so not checkable by simply reading it. Can you think of a way to avoid it?

2022-09-05 18:07 UTC, merged