D0.1 a 3 artificial objects
ROSA-project/ROSA-code pull request #31
Opened 2022-08-16 17:44 UTC by hfanahita

The code for this task is completed. Please let me know if there are any changes required.

2022-08-16 22:02 UTC, mehdi138r requested changes

2022-08-17 11:06 UTC, hfanahita commented on src/simulator/world.py
> +                    elif isinstance(self.registry.get_objects()[oid_1],
I don't think so. If we remove this condition, then when two non-physical objects intersect, the intersection instance will be added for both of them, which as we discussed in the last meeting, is not what we want.

2022-08-17 15:47 UTC, erfanz commented on src/simulator/world.py
> +                    elif isinstance(self.registry.get_objects()[oid_1],
@hfanahita 
Your code is essentially doing the follow: 
```
If A { ... }
elif B { ... } 
elif A and B { ... }
```
If both A and B are correct, the first `if` statement will get through, not the third one.

2022-08-18 11:00 UTC, hfanahita commented on src/simulator/world.py
> +                    elif isinstance(self.registry.get_objects()[oid_1],
Oh, sorry. You're right, so basically I should change my code to:
```
if A and B { ... }
elif A { ... }
elif B { ... }
else { ... }
```
Is that correct?

2022-08-18 11:22 UTC, mehdi138r commented on src/simulator/world.py
> +                    elif isinstance(self.registry.get_objects()[oid_1],
I think now it's correct.

2022-08-18 17:16 UTC, erfanz commented on src/simulator/world.py
> +                    elif isinstance(self.registry.get_objects()[oid_1],
@hfanahita 
Your change looks good. I think the code will be shorter and more readable if you use short-hand variables for `isinstance(self.registry.get_objects()[oid_X], non_physical_object.NonPhysicalObject)`.

2022-08-22 13:40 UTC, saeedafra requested changes

2022-08-22 13:40 UTC, saeedafra commented on src/simulator/world.py
> +                    # instance has to be added for intersections with physical objects only
it seems that he code is in good shape. Could you please add a TODO here just for reference, saying that this whole situation is temporary and at this stage our only nonphysicalobject is distance measurement beam. Thanks

2022-08-22 22:14 UTC, erfanz approved these changes

2022-08-23 10:50 UTC, saeedafra approved these changes

2022-08-23 10:50 UTC, merged